{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "1.7.0" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 8a41c31130622069de1cafc719b12cc0f765d57c3bd52724a9b5032249282275

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - numba <0.60.0
    - tqdm
    - anndata
    - typing-extensions
    - scikit-learn
    - omnipath
    - adjustText
    - scanpy
    - seaborn
    - pandas
    - scipy <1.14.0
    - numpy <2.0.0
    - typing_extensions
    - python-igraph >=0.10.0

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip
    - poetry

about:
  home: https://github.com/saezlab/decoupler-py
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
