{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "1.6.0" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: dde501f4d3e55a260f716e51b871bee403bc8aaa6b66799df0e42dee0787b98d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numba
    - tqdm
    - anndata
    - typing-extensions
    - skranger
    - scikit-learn
    - omnipath
    - adjustText
    - scanpy
    - seaborn
    - pandas
    - scipy
    - numpy
    - typing_extensions
    - python-igraph >=0.10.0

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saezlab/decoupler-py
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
