{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "1.5.0" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 1278b0912df0eb22618b720a7c862e6babd874472290e7c81c27dcf65c5bd48a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numba
    - tqdm
    - anndata
    - typing-extensions
    - skranger
    - scikit-learn
    - omnipath
    - adjustText
    - scanpy
    - seaborn

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saezlab/decoupler-py
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
